name = "Mini-game modpack"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9450b7da9a62ebb1e17c87610f62ece266e9925c8bbd0369a2005edc8d5f90b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/resources/datapack/required"
