name = "Mini-game modpack"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a5f61f38261afe0e6d9366a7f13685f339ec2266ac059bab5f7fa1b01d53a74"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/resources/datapack/required"
